### ISSUE TITLE
Principles & Goals of Project

### ISSUE THREAD

**Issue by JordanMartinez** [JordanMartinez/purescript-cookbook#1]
## Principles

- each recipe is a stand-alone Spago project that solves only 1 problem
- no or limited pedagogical explanations. If anything requires more explanation, link to other resources
- in the recipe's ReadMe
    - indicate which libraries are used/explained/demonstrated
    - **Added 6/7/2020**: Describe the problem the recipe solves

**Comment by JordanMartinez** [comment]
Remaining questions to be answered:
- How does Rust's cookbook work/look? (Copy success)
- If someone submits a recipe, what should the folder that contains the recipe be called, so that it doesn't lead to name clashing / merge conflicts?
- If multiple recipes on the same/similar topics are submitted, do we merge them into one? Keep them separate?

**Comment by JordanMartinez** [comment]
As I thought about this more today, I realized there's a tradeoff here in how we could approach things. In other words, whether to use 1 Spago project for each recipe or 1 Spago project for the entire repo:

## Use 1 Spago project for the entire repo

Pros:
- simpler CI build times and maintenance. Install `purescript`, `spago`, `parcel`, etc. and just run `spago test`

Cons:
- actual libraries used by example aren't shown
- merge conflicts might occur (A wants to use package set X whereas B wants to use package set Y)

## Use 1 Spago project for each recipe

Pros:
- each is stand-alone, so any modifications to it won't cause merge conflicts and whatnot
- libraries used are clearly visible
- different package set versions could be used in case one recipe becomes slightly outdated

Cons:
- We will compile the same code (e.g. Prelude) many times, slowing down CI. If we get too many recipes, we'll hit the CI build timeout. 

The Con to this one is not an issue right now, but could be in the future. Perhaps a possible solution is to run multiple builds that each test only a subset of the entire repo's recipes...?

**Comment by milesfrain** [comment]
I think we should do the single spago project strategy in the interest of keeping CI fast.
Including all libraries for the latest package set seems fine:
* It's straightforward to figure out what libraries are required for a given import (and if there's any ambiguity, that can be noted in that example's readme).
* We should aim to have everything work with the latest package set.
* TryPursuit uses this system.

It would be super cool if PS could maintain a global cache of versioned prebuilt libraries that are automatically linked to from each independent project. This is what Julia does, and it's pretty sweet.

**Comment by thought2** [comment]
I like the idea of having one `spago.dhall` file per recipe.

Assume there's one top level `packages.dhall` and each recipe has a `spago.dhall` that points to it.

I think if you do in CI 
`spago --config recipes/Foo/spago.dhall build`
`spago --config recipes/Bar/spago.dhall build`

then common dependencies are not built twice.

**Comment by JordanMartinez** [comment]
I believe this issue can now be closed. Some of the finer details of the principles/goals of this project will be further flushed out over time. However, I'd like to get people to start submitting recipe requests soon and implement those recipes. That'll provide more concrete cases as to where the current design fails.
