### ISSUE TITLE
Update error messages to indicate the correct recipe-script to use when running standardized script on wrong backend

### ISSUE THREAD

**Issue by JordanMartinez** [JordanMartinez/purescript-cookbook#10]
**Description of Problem**

See [my comment in #6](https://github.com/JordanMartinez/purescript-cookbook/pull/6#discussion_r438515582) and [my other comment]() for more context. We're currently using a standardized npm script to run a specific recipe using the npm config value. For example
```
npm run node --cookbook:recipe=MyRecipeName
npm run node --cookbook:recipe=BrowserExample
npm run browser --cookbook:recipe=HalogenExample
```
The problem arises when we use this standardized script to run a browser-only recipe. For example
```
npm run node --cookbook:recipe=HalogenApp
```
The error message should say "This recipe doesn't work on the Node.js backend. It only works on the browser backend. Please run `<correct command>` instead." (or vice versa for Node-only recipes)

Unfortunately, we currently get this:
```
$ npm run run --cookbook:recipe=RoutingHashHalogen

> cookbook@ run /home/jordan/Programming/Git Projects/purescript-cookbook
> spago run --main $npm_package_config_recipe.Main

[info] Installation complete.

[info] Build succeeded.
/home/jordan/Programming/Git Projects/purescript-cookbook/output/Effect.Aff/foreign.js:532
                throw util.fromLeft(step);
                ^

ReferenceError: window is not defined
    at exports.window (/home/jordan/Programming/Git Projects/purescript-cookbook/output/Web.HTML/foreign.js:5:3)
    at /home/jordan/Programming/Git Projects/purescript-cookbook/output/Effect/foreign.js:12:16
    at /home/jordan/Programming/Git Projects/purescript-cookbook/output/Effect/foreign.js:12:16
    at __do (/home/jordan/Programming/Git Projects/purescript-cookbook/output/Halogen.Aff.Util/index.js:36:183)
    at runAsync (/home/jordan/Programming/Git Projects/purescript-cookbook/output/Effect.Aff/foreign.js:98:20)
    at run (/home/jordan/Programming/Git Projects/purescript-cookbook/output/Effect.Aff/foreign.js:333:22)
    at /home/jordan/Programming/Git Projects/purescript-cookbook/output/Effect.Aff/foreign.js:639:15
    at drain (/home/jordan/Programming/Git Projects/purescript-cookbook/output/Effect.Aff/foreign.js:120:9)
    at Object.enqueue (/home/jordan/Programming/Git Projects/purescript-cookbook/output/Effect.Aff/foreign.js:141:11)
    at Object.run (/home/jordan/Programming/Git Projects/purescript-cookbook/output/Effect.Aff/foreign.js:638:23)
[error] Running failed; exit code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cookbook@ run: `spago run --main $npm_package_config_recipe.Main`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cookbook@ run script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jordan/.npm/_logs/2020-06-11T01_41_20_388Z-debug.log
```

**Comment by JordanMartinez** [comment]
There's a few ways we could approach this:
1. check whether the recipe has a specific file. If it does, then assume the recipe can be run for that particular target. This is easiest to do, but doesn't come with any real guarantees.
1. check whether a specific file in the recipe's folder that contains the backends for which it can compile contains the targeted backend. If it does, run the target; otherwise, print an error with list of targets. This is easier to maintain, but doesn't come with any real guarantees.
1. check the recipe's `spago.dhall` file and see whether a specific package is included in the list of dependencies (e.g. via `cat spago.dhall` plus some additional bash scripting). This is more reliable than other approaches, but can lead to false positives (i.e. someone installs a dependency they don't use)
1. attempt to run the program and print an error message encouraging user to try other targets. Probably the best way, but I'm not sure how to do this via `make` yet since every command run in `make` is done in a separate shell.

For 4, we could use `.ONESHELL` to remove that limitation, but I'm not sure whether that's desirable...

**Comment by milesfrain** [comment]
I'm thinking either 1 and/or 2 to generate all valid makefile targets.

We might also be able to do something clever to generate these from the recipe table.

We could then investigate CI options for running these recipes (I suspect there are a few good ways to do this). That will catch any invalid backends mistakenly marked as supported.

If the CI plans don't pan out, we could also include a note before the table of recipes with a link to a later "Troubleshooting" section that contains a few examples of errors encountered when attempting to run on an unsupported backend. For example: `ReferenceError: window is not defined` means `browser` is an invalid backend.

**Comment by JordanMartinez** [comment]
> For example: ReferenceError: window is not defined means browser is an invalid backend.

Thinking about this more... the error arises because `spago run` wraps the output of `spago build` in a `require(./output/Recipe.Main).main();` right? In other words, if we added a separate file that includes something like below and ran that script, it would suffice, correct?
```javascript
var script = require("./output/Recipe.Main);
try {
  script.main();
} catch e {
  console.log("This recipe cannot be run in the Browser.");
}
```
Then running a recipe would be
```
spago bundle-app -m Main -t file.js
node browserFile.js
```

**Comment by milesfrain** [comment]
That's worth a shot.

It may be good to reword the error message a bit to:
> The following error may be caused by incompatibility with the browser. See \<link to troubleshooting section in readme\> for more information.

Then rethrow the original error.

**Comment by JordanMartinez** [comment]
Yeah, that wording is better. Let's go with that.

**Comment by JordanMartinez** [comment]
I added a `node.js` file in the `RoutingHashHalogen` file:
```javascript
var script = require("../../output/RoutingHashHalogen.Main");
try {
  script.main();
} catch (error) {
  console.log("This recipe cannot be run on Node.");
  console.log("");
  console.log(error);
}
```
then ran `node recipes/RoutingHashHalogen/node.js`, which produced this output:
```
/home/jordan/Programming/Git Projects/purescript-cookbook/output/Effect.Aff/foreign.js:532
                throw util.fromLeft(step);
                ^

ReferenceError: window is not defined
    at exports.window (/home/jordan/Programming/Git Projects/purescript-cookbook/output/Web.HTML/foreign.js:5:3)
    at /home/jordan/Programming/Git Projects/purescript-cookbook/output/Effect/foreign.js:12:16
    at /home/jordan/Programming/Git Projects/purescript-cookbook/output/Effect/foreign.js:12:16
    at __do (/home/jordan/Programming/Git Projects/purescript-cookbook/output/Halogen.Aff.Util/index.js:36:183)
    at runAsync (/home/jordan/Programming/Git Projects/purescript-cookbook/output/Effect.Aff/foreign.js:98:20)
    at run (/home/jordan/Programming/Git Projects/purescript-cookbook/output/Effect.Aff/foreign.js:333:22)
    at /home/jordan/Programming/Git Projects/purescript-cookbook/output/Effect.Aff/foreign.js:639:15
    at drain (/home/jordan/Programming/Git Projects/purescript-cookbook/output/Effect.Aff/foreign.js:120:9)
    at Object.enqueue (/home/jordan/Programming/Git Projects/purescript-cookbook/output/Effect.Aff/foreign.js:141:11)
    at Object.run (/home/jordan/Programming/Git Projects/purescript-cookbook/output/Effect.Aff/foreign.js:638:23)
[error] Running failed; exit code: 1
```
I presume this is caused by `runHalogenAff`?

So, it doesn't look like my "script wrapper" idea will work...
