### ISSUE TITLE
Update instructions for creating new recipe to ensure one determines a folder name to prevent name clashing

### ISSUE THREAD

**Issue by JordanMartinez** [JordanMartinez/purescript-cookbook#11]
**Description of Problem**

See [my comment in #6](https://github.com/JordanMartinez/purescript-cookbook/pull/6#discussion_r438516319) for more context. Essentially, if Developer A starts working on a new recipe at the same time as Developer B and they both submit a PR at the same time using the folder "MyCoolRecipe" name, it will create name clashing and cause a merge conflict if we wanted to merge them both.

It would be better if they opened an issue and got approval for a folder name before working on their PR. We need to update the instructions to clarify that.

**Additional context**

**Comment by milesfrain** [comment]
I think the bigger risk is having two contributors duplicate work for similar recipes, since the merge conflicts can easily be resolved by just renaming one of the directories.
But this resolves both of those concerns, so all for it.

**Comment by JordanMartinez** [comment]
Yeah, that's actually a better reason for this :smile:
