### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by thomashoneyman** [JordanMartinez/purescript-cookbook#116]
**Description of Problem**

Debugging can be non-obvious to PureScript beginners. First, you can't insert log statements in pure code, and second, you can only log `String` values, so if your data doesn't have a `Show` instance you're out of luck.

The `Debug.Trace` module has plenty of helper functions that help with this. The two I use the most are `spy` and `traceM`, but on the whole this package lets you get "print debugging" when you temporarily need it. Even better, these functions carry a compiler warning that helps you remember to remove the statements before say opening a pull request.

A useful recipe might show how to insert debugging statements into pure (and/or effectful) code using various functions from the `Debug.Trace` modules.

**Proposed Name of Folder/Module**

```
Unique Recipe Name: Debug
```

**Comparison to other recipes**

Other recipes use logging as a proof that they work, but none show how to use `Debug.Trace` to log pure code or insert temporary statements. This module is a simple but immediately useful tool to know about.

**Comment by JordanMartinez** [comment]
Good idea, @thomashoneyman!

**Comment by JordanMartinez** [comment]
I think this recipe should show a couple of things:
- using `spy` to print the value of a primitive type (e.g. `4`, `true`, `"my string"`)
- using `spy` to show that printing a function doesn't work (I've never done this before, so I assume that's the case)
- using `spy` to print an ADT (e.g. `data MyFoo = Foo Int (Tuple Int Int) { bar :: String }`)
- using `traceM` to do all of the above in normal `Effect` (i.e. show that synchronous effect produces predictable output)
- using `traceM` to do all of the above in `Aff` while racing 3 or more effects (i.e. show that asynchronous effect produces unpredictable output)
- using `traceM` to do all of the above in `ST`

**Comment by thomashoneyman** [comment]
You can print a function (though you usually don’t want to, as it’s not usually that useful)

**Comment by JordanMartinez** [comment]
I'm claiming this one.
