### ISSUE TITLE
Determine standard "npm run X" script names

### ISSUE THREAD

**Issue by JordanMartinez** [JordanMartinez/purescript-cookbook#12]
**Description of Problem**

I like how each recipe can use one of the following "command scripts" to run their corresponding part:

    run
    serve
    build-dev
    build-prod

I feel like we should standardize on this. I can think of a few examples

    node = run a Node-only recipe
    node-cli = run a Node-only recipe that takes arguments like a CLI program would
    browser-dev = run a browser-only recipe using developer-level settings
    browser-prod = run a browser-only recipe using production-level settings
    test-ci = run this script during CI to ensure the recipe is still up-to-date
    clean = clean a single recipe
    clean-all = clean the entire repo
    initialize = alias for `npm i && spago build`, which will install and setup the necessary dependencies

Which names should we use and what is their corresponding purpose? How do we make this clear, short, and keep the number of names small?

**Comment by JordanMartinez** [comment]
@milesfrain It seems like we're standardizing on `run` for Node and `serve` for the Browser. I think we should change `run` to `node` and `serve` to `browser` as it will be clear which backend we are targeting. Thoughts?

**Comment by milesfrain** [comment]
Sounds good to me.
