### ISSUE TITLE
AceEditorHalogen

### ISSUE THREAD

**Issue by milesfrain** [JordanMartinez/purescript-cookbook#120]
```
Unique Recipe Name: AceEditorHalogen
```

**Description of Problem**

Port [Halogen's Ace Editor](https://github.com/purescript-halogen/purescript-halogen/tree/master/examples/ace) example to Halogen Hooks.

There's a partial snippet in https://github.com/thomashoneyman/purescript-halogen-hooks/issues/48

One todo is adding `ace` to the package set.
https://pursuit.purescript.org/packages/purescript-ace/7.0.0

**Comment by JordanMartinez** [comment]
Sounds good to me!

**Comment by JordanMartinez** [comment]
Closing as this is now a duplicate of #138.

**Comment by JordanMartinez** [comment]
I'm reopening this until #162 gets merged.

**Comment by JordanMartinez** [comment]
Closed by #162
