### ISSUE TITLE
Thoughts on standardizing "targets"?

### ISSUE THREAD

**Issue by JordanMartinez** [JordanMartinez/purescript-cookbook#123]
So far, we've been unofficially following a naming convention. Depending on which library/interaction is used, a suffix is being added to the recipe name:
- `*Halogen` = Halogen is being used
- `*React` = React is being used
- `*CLI` = Node is being used and it involves user interaction
- `*Node` = Node is being used and no user interaction occurs

Would we like to keep using this convention? If so, perhaps there's a few others we can add

- `*Js` = plain JavaScript is being used (i.e. no framework like Halogen/React/Concur)
- `*Concur` = Concur is being used (if and when we get a PR for it)

**Comment by and-pete** [comment]
Should a `*HalogenHooks` be distinct from `*Halogen`?. Would you expect to offer the same recipes both using hooks and as regular components enough to warrant it? Or is it a safe bet at this stage that the hooks approach is going to be defacto entry point for people starting out with Halogen going forward?  I know @milesfrain touched on it elsewhere (in https://github.com/JordanMartinez/purescript-cookbook/issues/86#issuecomment-650378098)

**Comment by milesfrain** [comment]
I see benefits of including both Halogen versions, but I suspect Hooks would be more common. What about:
* `Halogen` (implies hooks)
* `HalogenClassic` (no hooks)

**Comment by JordanMartinez** [comment]
Classic is a bit long though of a name `TextFieldsHalogenClassic`. Would we also use `TextFieldsReactClassic` to distinguish that from their hooks version?

**Comment by milesfrain** [comment]
Yes, assuming that there aren't going to be many "Classic" recipes. I suspect Hooks is even more common for React than Halogen.

And I don't think an occasional longish name is an issue, especially when the name is only two characters longer than the "HalogenHooks" naming proposal.

**Comment by JordanMartinez** [comment]
> And I don't think an occasional longish name is an issue, especially when the name is only two characters longer than the "HalogenHooks" naming proposal.

True. I think my main issue with using `Classic` is that I don't find that very meaningful. In my mind, Halogen either has a component version or a hook version. In my mind, it's clearer which one we are referring to if we use `HalogenComponent` rather than `HalogenClassic`.

If we wanted to abbreviate them (and document that in the Readme and corresponding `make list` command), perhaps we could settle with these names:
- `HalogenComp`
- `HalogenHook`

Thoughts?

**Comment by milesfrain** [comment]
Thinking `HalogenHooks` over `HalogenHook`.

And if we're using the hooks suffix, then regular halogen can just be `Halogen`, but I don't have strong feelings on that suffix.

If we end up with over 100 halogen recipes where 90% of them are `Hooks`, then we can revisit this and script a batch rename if we find that improves ergonomics.

**Comment by JordanMartinez** [comment]
> And if we're using the hooks suffix, then regular halogen can just be Halogen, but I don't have strong feelings on that suffix

The only issue I see with this is if one was searching for just plain `Halogen` recipes.

Regardless, I think this is "good enough" for the time being. Shall we standardize on the following then?
- `*Halogen` = Halogen (non-hook version) is being used
- `*HalogenHooks` = Halogen (hook version) is being used
- `*React` = React (non-hook version) is being used
- `*ReactHooks` = React (hook version) is being used
- `*Concur` = Concur is being used (if and when we get a PR for it)
- `*Js` = plain JavaScript is being used (i.e. no framework like Halogen/React/Concur)
- `*CLI` = Node is being used and it involves user interaction
- `*Node` = Node is being used and no user interaction occurs

**Comment by milesfrain** [comment]
> The only issue I see with this is if one was searching for just plain `Halogen` recipes.

That's a good point, and renaming would also be easier with a suffix. Just not sure what that suffix should be. Your proposal looks good otherwise.

To confirm, I assume we're not planning on featuring any [non-basic React](https://github.com/purescript-contrib/purescript-react) recipes.

Do we expect any non-hooks React recipes either?

> I think my main issue with using `Classic` is that I don't find that very meaningful. In my mind, Halogen either has a component version or a hook version. In my mind, it's clearer which one we are referring to if we use `HalogenComponent` rather than `HalogenClassic`.

Doesn't Halogen Hooks also use "Components"? And [react-basic](https://github.com/lumihq/purescript-react-basic#getting-started) is also using the `classic`/`hooks` naming convention. So I think sharing that naming scheme between frameworks would be nice for consistency.

**Comment by JordanMartinez** [comment]
> To confirm, I assume we're not planning on featuring any non-basic React recipes.

Probably not. I think most people use `react-basic`. If we have multiple Reacts, that will get confusing quickly.

> Doesn't Halogen Hooks also use "Components"?

Sort of...? While a Hook ultimately has to be converted into a component via `Hooks.component \_ _ -> ...`, the implementation style / approach is still a Hook, not a Component.

> And react-basic is also using the classic/hooks naming convention. So I think sharing that naming scheme between frameworks would be nice for consistency.

I didn't know about that. `Classic` is less to type than Component, so I'm in favor of Classic now with this additional information. Otherwise, we may have JS devs come to PureScript and be a bit confused by the lack of classic/hooks distinction. We can also further clarify these distinctions in the Readme / `make list`.

**Comment by ptrfrncsmrph** [comment]
I thought that `react-basic` was using "classic" in reference to React's `class`-based components (which hooks present an alternative to). I might be wrong, since I don't think I've heard "classic" used to refer to OOP _classes_ before (the closest that comes to mind is the phrase _classical inheritance_), so maybe it's just used in the sense of "traditional" or something? If it does refer to `classes`, would that still make sense applying that term to non-hooks Halogen?

**Comment by milesfrain** [comment]
I've always read "Classic" as "Traditional" / "Original".

**Comment by JordanMartinez** [comment]
I'll be submitting a PR to address this soon.
