### ISSUE TITLE
Ensure each recipe has a 'run-ci' script that can be executed via a `npm run` script

### ISSUE THREAD

**Issue by JordanMartinez** [JordanMartinez/purescript-cookbook#14]
**Description of Problem**

This exists to ensure documentation stays up-to-date. Each recipe must define a way to verify that it continues to work by passing CI. How it does that should be on a case-by-case basis.

**Comment by JordanMartinez** [comment]
Here's my current thoughts on this issue.

We should stop using `buildAllDev` as every recipe's CI for a few reasons:
1. Not every recipe needs to use `parcel` to work. At the very least, this might reduce CI build time. 
1. There may be some recipes that actually need to run on Node to verify that they work (i.e. they don't throw an exception). 
1. Some recipes' CI might be verifying that they compile. For example, if someone wanted to add a recipe for `purescript-optparse`, we wouldn't be able to run the recipe in CI because it requires user input.

**Comment by JordanMartinez** [comment]
I've been trying to get this to work via the conditional syntax (general idea below) based on [this SO answer](https://stackoverflow.com/a/20566812). Unfortunately, it doesn't work.
```make
%-testNode: $(call recipeDir,%)
ifeq ($(shell test -f $(call nodeSupported,$*) && echo -n yes),yes)
> echo test node
else
> echo recipe not have node test
endif

**Comment by milesfrain** [comment]
> We should stop using `buildAllDev` as every recipe's CI for a few reasons:

Hoping that #58 address a few of these concerns.

Node targets are tested with `runAllNode`. We can work around the `optparse` dilemma by letting that file flag be something like `nodeSupportedSkipCI.md`.

Web targets are tested with `buildAllWeb`. I think it's nice to keep this step to ensure everything is hooked up correctly. For example, this will catch some typos in `index.html` and `index.js`. It currently takes about 4 seconds per recipe. We can also investigate speeding this up with a faster bundler, such as [esbuild](https://github.com/evanw/esbuild).

**Comment by milesfrain** [comment]
> We can also investigate speeding this up with a faster bundler, such as [esbuild](https://github.com/evanw/esbuild).

Gave `esbuild` a try and found it to be 50x faster than `parcel`, but it doesn't support `.html` entry points (on the roadmap). Let's revisit this when we have more recipes and can compare it to parcel v2 (#47).

```shell
$ time esbuild --bundle web/index.js --outdir=web-dist
0.26s user 0.05s system 284% cpu 0.107 total
$ time NODE_ENV=development parcel build web/index.js --out-dir web-dist --no-minify 
15.19s user 0.80s system 286% cpu 5.572 total
```

**Comment by JordanMartinez** [comment]
> Gave esbuild a try and found it to be 50x faster than parcel, but it doesn't support .html entry points (on the roadmap). Let's revisit this when we have more recipes and can compare it to parcel v2 (#47).

Sounds good.

**Comment by JordanMartinez** [comment]
I'm starting to wonder whether just using `.ONESHELL` might solve this problem. In such a situation, we could just use bash to fix these issues while using `make` to provide arguments.
