### ISSUE TITLE
How to create a heterogeneous array in Purescript

### ISSUE THREAD

**Issue by afcondon** [JordanMartinez/purescript-cookbook#149]
**Recipe Name**

```
HeterogenousArray
```

**Recipe Description**

Briefly explain that the type system explicitly prohibits naive heterogeneous collections and show how one can achieve the result when necessary using `purescript-variant`

**Comment by milesfrain** [comment]
More `variant` examples would be great.
That topic can be pretty confusing the first time through, even with the [guide](https://github.com/natefaubion/purescript-variant/blob/master/README.md#documentation).

**Comment by afcondon** [comment]
i just discovered this library: https://github.com/athanclark/purescript-tuples-native

...which is another take on handling heterogenous arrays as nested tuples. 

Not proposing adding it to the recipe or re-opening this, just FYI

Would make a good blog post comparing the three, tho

**Comment by milesfrain** [comment]
I feel like an FFI example is necessary to showcase `tuples-native`.

Is there a use case outside of FFI?

**Comment by afcondon** [comment]
I wouldn’t think so - I’m not sure what I think of it as an approach but it does have a certain simplicity on its side for FFI
