### ISSUE TITLE
Prefix any JS files with "use strict;" also use `jshint`?

### ISSUE THREAD

**Issue by JordanMartinez** [JordanMartinez/purescript-cookbook#15]
**Description of Problem**

[See this comment from #6](https://github.com/JordanMartinez/purescript-cookbook/pull/6#discussion_r438521431)

**Comment by paluh** [comment]
I'm not sure if this is valuable suggestion as not everyone uses `jshint` but in our projects it is a required liter so we try to use also these headers:

```javascript
/* global exports, require */
/* jshint -W097 */

"use strict";
```

On the server side we use:

```javascript
/* jshint node: true */
/* jshint -W097 */

"use strict";
```

**Comment by JordanMartinez** [comment]
I'm not against using `jshint`. For now, I only want to add the `"use strict";` part. I think I would like to revisit this after getting more of this cookbook setup.

**Comment by JordanMartinez** [comment]
The recipes included in this cookbook will cover a number of different things. At some point, I imagine that someone will show how to use FFI to correctly wrap a binding or deal with miscellaneous things (e.g. how to use TypeScript as an FFI rather than JavaScript). It would likely make sense to use `jshint` in those recipes. However, in our `dev/index.js` files (which are now the `web/index.js` files), even adding `"use strict";` is a bit overkill. I'd still rather have it just in case, but I don't think it's absolutely necessary. If we did add `jshint` as well, I think that would be overkill.

Moreover, adding `jshint` here would require downloading an npm dependency, which I would prefer not to do unless it is needed to run a recipe.

So, I think I'll close this issue. If you disagree, please open a new one issue rather than reopening this issue. Right now, this issue seems to have been taken beyond its original scope (i.e. adding `"use strict";` which was done in #38) and thus doesn't feel very "actionable."
