### ISSUE TITLE
Time examples not showing local time

### ISSUE THREAD

**Issue by ptrfrncsmrph** [JordanMartinez/purescript-cookbook#167]
**Describe the bug**

The `TimeReactHooks` and `TimeHalogenHooks` have different behavior than the Elm example.

**To Reproduce**

1. Clone this repo
2. Run `make TimeReactHooks-web` (or `make TimeHalogenHooks-web`)
3. Go to http://localhost:1234 (or wherever the recipe app is running)
4. Compare the output to https://elm-lang.org/examples/time

**Expected behavior**

I would expect the time displayed to be equivalent, but it seems that the Elm example shows the current time according to my locale (EDT), the recipe examples seem to show GMT.

**Screenshots**

<img width="277" alt="image" src="https://user-images.githubusercontent.com/26548438/87252528-d5605500-c441-11ea-811c-a1f67bc91d2e.png">

**Environment:**

- OS: MacOS
- Browser (if applicable): Firefox
- Node Version: 
- Spago Version: 0.15.3
- PureScript Version: 0.13.8

**Additional context**

**Comment by ptrfrncsmrph** [comment]
Not sure the solution here, might need to use [`Data.JSDate`](https://pursuit.purescript.org/packages/purescript-js-date/6.0.0/docs/Data.JSDate) to get local time?

**Comment by milesfrain** [comment]
Yeah, this is not ideal.

Some other discussion about this in: https://github.com/JordanMartinez/purescript-cookbook/pull/115#issuecomment-652742191

There's a note about UTC display in the [halogen recipe readme](https://github.com/JordanMartinez/purescript-cookbook/blob/master/recipes/TimeHalogenHooks/README.md#browser):
> The browser will display the current time in UTC, not the end-user's computer's time zone.

But it would definitely be better to match Elm behavior.

**Comment by milesfrain** [comment]
> Not sure the solution here, might need to use [`Data.JSDate`](https://pursuit.purescript.org/packages/purescript-js-date/6.0.0/docs/Data.JSDate) to get local time?

That sounds good.
Elm also uses `Date()`.
https://github.com/elm/time/blob/1.0.0/src/Elm/Kernel/Time.js#L32

**Comment by milesfrain** [comment]
Fixed in #179
