### ISSUE TITLE
Read from a file

### ISSUE THREAD

**Issue by ptrfrncsmrph** [JordanMartinez/purescript-cookbook#170]
**Recipe Name**

```
ReadFromFile
```

**Recipe Description**

Use one of the wrappers around Node's `fs` module to read from a file.

**Comment by JordanMartinez** [comment]
There's already `ReadAndPrintFileContents`, so I'm assuming you have something different in mind here?

**Comment by ptrfrncsmrph** [comment]
Oops, I didn't see that one

**Comment by JordanMartinez** [comment]
I'm not sure this should be closed. You could show how to read a file via Streaming or something.

**Comment by ptrfrncsmrph** [comment]
That's true, I would be interested in seeing that, though I originally had in mind just the simple thing that was already covered. Maybe there should be a separate `ReadFromFileStreaming` or something? Not sure what to call it.

**Comment by JordanMartinez** [comment]
I think `StreamingReadFile` is a bit better. Go for it!
