### ISSUE TITLE
Autocomplete/typeahead recipe using Halogen Select

### ISSUE THREAD

**Issue by AhmedAnwarHafez** [JordanMartinez/purescript-cookbook#194]
**Recipe Name**

```
HalogenSelect
```

**Recipe Description**

A recipe that demonstrates a basic example on using autocomplete or typeahead using [Halogen Select](https://github.com/citizennet/purescript-halogen-select/).

**Comment by JordanMartinez** [comment]
Doesn't [Halogen Select already have examples](https://github.com/citizennet/purescript-halogen-select/tree/master/examples) that show how to do that?
