### ISSUE TITLE
Fix Broken React Examples in Try PureScript

### ISSUE THREAD

**Issue by milesfrain** [JordanMartinez/purescript-cookbook#196]
@spicydonuts and @ptrfrncsmrph, do either of  you have suggestions for how to get the React examples working in the Try PureScript environment?

It's currently having issues finding the container (see dev console):
[Broken - ButtonsReactHooks](https://try.ps.ai/?github=JordanMartinez/purescript-cookbook/master/recipes/ButtonsReactHooks/src/Main.purs)

The Halogen examples work great:
[Working - ButtonsHalogenHooks](https://try.ps.ai/?github=JordanMartinez/purescript-cookbook/master/recipes/ButtonsHalogenHooks/src/Main.purs)

One workaround is to reuse Halogen's `awaitBody` in the React example, but it would be better to eliminate that Halogen dependency. Also, react dom complains in the dev console about rendering into the document body.
[Working with Halogen's `awaitBody`](https://try.ps.ai/?gist=d69f7a27fc206e66a49ebe81d8ac1f72)

**Comment by spicydonuts** [comment]
https://try.ps.ai/?purs=LYewJgrgNgpgBAWQIYEsB2cDuALGAneAWkLgHkA3fTPFAF1pgwCMBPOAFTzYAUICBlAMY0ADrQBQ4lMBEg8tONwJQIYGFJlyFAESS0kAOmQsm8ABTHTZgwYCUtjbPlwAogDM3MQQrPvP3h2knBT8vWgMXAA9BGDEUEAwzWmw8EExAzWcAJRgkbwMAISQAZxRBA21SBDgzAjQ1PAzguBy88KLS8srqkpbHLRbc-I6yiMo0WmKa7CR62DwAfSaB1uGS0YAJEBAAaymzAGEQTTRGWgAaOEFj2VOJy4himH59BkuzAHoAHXt+7KH2utyltdlNeqsJEEBgB1GBMAwbdgIAAyNUw6DAaWWzlh8MRKIRSOR2hAgggwDONSY4BY2IUuMJBPxyJcsApEzgvWZrJg7MhmXpcMZyIM0IxaRqmLJfIc4mAqAwAC5Fa4PGE4ABVNB0OUKuAAXjgmPEcDg1LAbAAPCRzWx9ZbLUbSeTKfbHej6mkTVcSvBbXAQG5vaaAHIgZLoADmcEIAD44MlUpg4AAiI7QMBwNDhuBuDFmmkGFPBuAAKUeCkEMfjxtNdbNEHoCSm1rgwB2BUbtGbJdNdQaVK7zbgAG8AL62GrctlnAzdnl8q6y9udptoKbKuBHE6U8dyjtD9cGp3e647jkp1fd9cpuBfBbVwZtAy1uvXCAc75wJ60dMc1uPM8rzwAADCWsASPWpozHMMAHFAZQ7MeMFgPMD4Oo6P5-pBdYiHw6hQXAAAkLQvig5ALL2UEANqkUwh6jgGaDwYhKoobALGCEhZgPiQACMtiXII2AoFAYB1CqtFZHOMCRAoKaELeAC6cBjlR9aXNJYDkQ+UkyXJNTFNgErvhMk5KepdaaQY9FroxCScTsbGzKhcEIVxNQPgA1HAAlCSJYkSXAekMAZKZecpqmWaaFlAA
