### ISSUE TITLE
BehaviorSuperCircleJs

### ISSUE THREAD

**Issue by milesfrain** [JordanMartinez/purescript-cookbook#214]
**Recipe Name**

```
BehaviorSuperCircleJs
```

**Recipe Description**

Port @i-am-tom's [Super Circle](https://github.com/i-am-tom/purescript-super-circles) game.

This will be a nice demonstration of the `behavior` library (and a contrast to our existing game recipes that use the `signal` library).

@i-am-tom, do we have your permission to copy and edit your work here under the MIT license?

@vladciobanu, I see you were looking for an open recipe request in your stream. Would you like to tackle this one?

**Comment by JordanMartinez** [comment]
Just a thought. If this shows off the `behavior` library, should that have its own prefix like Halogen and React?

**Comment by i-am-tom** [comment]
Hey - I would absolutely be OK with this! I feel honoured 😳 

If it helps, there's a talk to go with it https://www.youtube.com/watch?v=DWNnPh0o4NE

**Comment by milesfrain** [comment]
> If this shows off the `behavior` library, should that have its own prefix

I assume you mean a [reserved](https://github.com/JordanMartinez/purescript-cookbook#current-recipe-suffixes) _suffix_. Let's see how many more of these recipes are created. If any are duplicated across libraries, then it makes more sense to switch to a suffix to keep them adjacent in the recipe list.

**Comment by JordanMartinez** [comment]
Yeah, I mean suffix :sweat_smile: Ok, sounds good!
