### ISSUE TITLE
Only run CI on `master` branch?

### ISSUE THREAD

**Issue by JordanMartinez** [JordanMartinez/purescript-cookbook#22]
Following up from #21, should we only run CI on the `master` branch? I don't think we need to run it on anything else, but this is also a minor issue that can be resolved when it becomes a problem.

**Comment by milesfrain** [comment]
I think it's desirable to run _testing_ CI on all branches. That way a PR on an existing PR branch will be tested. PR builds might still be automatic regardless of this setting.

_Asset generation_ (e.g. publishing mdbook) should be restricted to only `master`, and that's handled with sane defaults with `provider: pages` (for `gh-pages` branch).

In conclusion, we shouldn't need to touch the `branches` setting.

https://docs.travis-ci.com/user/customizing-the-build/#building-specific-branches

**Comment by JordanMartinez** [comment]
> I think it's desirable to run testing CI on all branches. That way a PR on an existing PR branch will be tested. PR builds might still be automatic regardless of this setting.

True. Closing this issue then.

> Asset generation (e.g. publishing mdbook) should be restricted to only master, and that's handled with sane defaults with provider: pages (for gh-pages branch).

This might be a separate issue, but I hate the idea of using two separate branches. If `gh-pages` is what the branch name needs to be for the website to be served via GH, then is it possible to rename `master` to `gh-pages`? Or perhaps it should be a separate repo primarily for this purpose...?

**Comment by milesfrain** [comment]
> If `gh-pages` is what the branch name needs to be for the website to be served via GH, then is it possible to rename `master` to `gh-pages`? Or perhaps it should be a separate repo primarily for this purpose...?

The `gh-pages` branch is just where the autogenerated html files are dumped during CI merge/deploy:
https://github.com/purescript-contrib/purescript-book/blob/master/.travis.yml
https://github.com/purescript-contrib/purescript-book/tree/gh-pages

**Comment by JordanMartinez** [comment]
Looks like they've updated things since I last looked at GitHub Pages. See [choosing a pubishing source](https://help.github.com/en/github/working-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#choosing-a-publishing-source). You can chose to use the `gh-pages` branch, the `master` branch, or the `docs/` folder in the `master` branch. Of these three, I think the `docs/` folder makes sense.

**Comment by milesfrain** [comment]
With `docs` folder strategy:
* Con: Additional commit noise and larger checkouts.
* Pro: Offline html viewing.

Let's try `docs` strategy for this repo and see how that experience compares to `gh-pages` with the other book.

**Comment by JordanMartinez** [comment]
`docs`-approach it is!
