### ISSUE TITLE
Payload HTTP Backend Example

### ISSUE THREAD

**Issue by vladciobanu** [JordanMartinez/purescript-cookbook#225]
**Recipe Name**

```
PlayloadHttpApiNode
```

Each recipe name must be unique. Use PascalCase.

**Recipe Description**

A simple API example for the strongly typed HTTP backend payload. Ideally, it would show an API that allows for get all, get by id and insert, at least.

I already implemented something using `AVar`, and I was wondering whether this is too complicated for a single recipe? The alternative would be using files instead (to keep state across calls), but then it would also complicates matters due to encoding/decoding.

Do you think it would be an useful recipe?

PS: I cannot use `StateT` because it's not currently possible yet (in payload). I added an issue, and am willing to update this when/if it gets resolved.

**Comment by JordanMartinez** [comment]
> I cannot use StateT because it's not currently possible yet (in payload). I added an issue, and am willing to update this when/if it gets resolved.

If you use `StateT`, it would likely not produce the behavior you want. `StateT` threads state through a function call. I believe each request-response would start with the original value passed to the `StateT` computation, not the latest value.

**Comment by JordanMartinez** [comment]
> I already implemented something using `AVar`, and I was wondering whether this is too complicated for a single recipe? The alternative would be using files instead (to keep state across calls), but then it would also complicates matters due to encoding/decoding.

`AVar` is fine. If we wanted to do this properly, we might use the ReaderT pattern, similar to what I did in the random number game. However, that might get too complicated for little benefit. This recipe highlights how one can build an HTTP server quickly using the library.

**Comment by milesfrain** [comment]
> PS: I cannot use `StateT` because it's not currently possible yet (in payload). I added an issue, and am willing to update this when/if it gets resolved.

Issue for reference: https://github.com/hoodunit/purescript-payload/issues/7

**Comment by milesfrain** [comment]
We're able to get really great insights into cookbook usability by reviewing your stream of submitting a recipe:
* Making request issue: https://www.twitch.tv/videos/721301879?t=1h45m20s
* Making request PR: https://www.twitch.tv/videos/721301879?t=2h10m59s
* After Package set detour: https://www.twitch.tv/videos/721301879?t=2h29m40s

Kudos for adding `payload` to the package set.

Also, feel free to **suggest ways that we could make the cookbook more user-friendly**. For example with our organization, the instructions we're giving to users, available issue templates, or anything else.

Some comments from reviewing the stream:
* Github doesn't allow self-assignment without being a collaborator on the repo. isaacs/github#100
* If you make a recipe typo, you can simply use `scripts/newRecipe.sh` to create a new recipe from your misspelled one with the correction, then delete the misspelled directory.
* The common commands to build+run recipes are printed by running `make list` (or just `make` without arguments). They're also listed under [Running Recipes](https://github.com/JordanMartinez/purescript-cookbook/blob/master/README.md#running-recipes) and [printed](https://github.com/JordanMartinez/purescript-cookbook/pull/186#issuecomment-659895793) after running `newRecipe.sh`.
* The non-traditional cookbook directory structure does not play nice with most IDE configurations. I'll make an issue for this and a note in the docs.

I'll make a PR with these changes to improve the instructions:
* Show how `newRecipe.sh` can be used to rename recipes.
* Note that `newRecipe.sh` [prints relevant commands](https://github.com/JordanMartinez/purescript-cookbook/pull/186#issuecomment-659895793).
* Convert recipe [template selection list](https://github.com/JordanMartinez/purescript-cookbook/blob/master/CONTRIBUTING.md#goal-2-setup-a-new-recipes-boilerplate-by-copying-a-current-similar-one) to a table.
* Link to [Running Recipes](https://github.com/JordanMartinez/purescript-cookbook/blob/master/README.md#running-recipes) from Contributing.md.

Git Tips:
* Create a branch based on master:
  * git checkout -b my-new-branch master
* Update master:
  * git pull --rebase upstream/master
* Nice display of SHAs for all branches (for cherry-pick purposes):
  * `git all` with this alias https://github.com/milesfrain/configs/blob/e5111c70c998188a73279f8bec79ba4badac6086/core/.gitconfig#L19

A note on branch naming:
I notice you're naming branches with a forward slash. This unfortunately confuses TryPureScript github path parsing, and prevents posting a [demo link](https://github.com/JordanMartinez/purescript-cookbook/pull/224#issue-472178960) for us to preview before the recipe is merged. This is irrelevant for this particular node-only recipe, but swapping the slash for a hyphen would make it easier to review future TPS-compatible recipes.
