### ISSUE TITLE
Reconsider the tools used to run recipes to account for multiple parties' interests

### ISSUE THREAD

**Issue by JordanMartinez** [JordanMartinez/purescript-cookbook#24]
While trying to research multi-line npm scripts, I found this package: [script-launcher](https://www.npmjs.com/package/script-launcher). Thoughts on using it here?

**Edit:** See the next comment I make for the heart of this matter.

**Comment by milesfrain** [comment]
Yes, that looks really nice. Seems like we could also specify web vs node compatibility per recipe within the menu config.

**Comment by JordanMartinez** [comment]
Ok, let me put this a different way, starting from the top-down principle-first approach.

- [Users] - We want users to be able to clone this repo and be able to easily run whichever recipe they desire. They should not have to worry about installing npm dependencies unless a recipe requires it (e.g. reduce possible attack surface). We want to eliminate annoying errors when possible (i.e. #10) or minimize them by providing helpful action-oriented error messages. The commands to run the scripts should read from 'left-to-right,' the order in which our brains will think of those recipes. For example, something like `npm run MyRecipe --target=browser` or `npm run MyRecipe --target=production-thingy-majiggy`. Not right-to-left as we currently have things npm run production-thingy-majiggy --recipe=MyRecipe`. While these could be standardized (e.g. #12), it wouldn't be required in this approach.
- [Reciper-Makers] - We want those who write recipes to have full freedom in how they implement their recipe. If they want to have 10 different ways to build a recipe, that should be possible. For example, a complicated recipe might have 2+ targets (i.e. build the webapp server, build the client part, build the file server, build the database server). While I would likely reject a recipe that does all of that (rather than multiple recipes that do that individually), it should still be possible and easy to do. Moreover, the scripts themselves should be stand-alone and be stored within the same folder as their recipe.
- [Maintainers] - We want maintainers to be able to add/tweak/modify one recipe without affecting all others. We want CI to be simple and clear. In other words, let's say I had a recipe in the `MyCoolRecipe` folder that suddenly became broken at some point (e.g. package set issue, breaking release in a library, breaking release in PS, etc.). The only thing I should have to do is move the `MyCoolRecipe` folder from `src/` into `broken/`. CI should pass after that if nothing else is affected.

Our options are currently
- `npm` scripts. These suck because they don't scale well
- `script-launcher`. This provides a better UI, but is still based on `npm` scripts. I'm not sure how well it would scale, and it needs more research
- `make`. I'm not familiar with using this, but I believe it's a better candidate than our other proposed tools. My only question is whether a person's computer would always have it installed or whether we would need to include instructions for that.

**Comment by milesfrain** [comment]
>     * My only question is whether a person's computer would always have `make` installed or whether we would need to include instructions for that.

Should be installed by default on linux.
On osx it will prompt you to install xcode.
Not sure what the story is with windows.

**Comment by JordanMartinez** [comment]
> Not sure what the story is with windows

Seems like `make` is accessible via the [Linux Subsystem](https://stackoverflow.com/a/54133058). [Installing it via `chocolatey` also works](https://stackoverflow.com/a/54086635). Installing it is `choco install make`. 

I think it's worth trying out here. I can play with the script-launcher to see how well that works, too. Thoughts?

**Comment by JordanMartinez** [comment]
After looking at `script-launcher` and `make`, I think `make` works best.

**Comment by milesfrain** [comment]
I'll give `make` a shot. In the meantime we should merge #25 then #26 to get things back to a working state.

**Comment by JordanMartinez** [comment]
I'll change the default to 'squash and merge.' I don't think I have a preference.

**Comment by JordanMartinez** [comment]
> In the meantime we should merge #25 then #26 to get things back to a working state.

Merged.

**Comment by JordanMartinez** [comment]
I'm finding this tutorial helpful in getting me up to speed: https://makefiletutorial.com/

**Comment by JordanMartinez** [comment]
I think the idea I have in my head looks something like this:

User calls `make` and it prints out the following:
```
=== SCRIPTS ===
`make` - output this help text
`make help` - output this help text
`make build` - Setup this cookbook
`make clean` - Clean up all files in this cookbook
`make list` - only list the recipes you can call
`make <RecipeName>` - list the targets for a given recipe
`make <RecipeName> <target>` - Run the recipe for a given target

=== RECIPES ===
RoutingHashHalogen - Do hash-based routing in a Halogen app
RoutingHashLog - Log the route that would be created via hash-based routing
RoutingPushHalogen Do push-state routing in a Halogen app
```
User then calls `make RoutingHashHalogen` and the following is outputted
```
Recipe Name: RoutingHashHalogen
Description: Do hash-based routing in a Halogen app

[Targets]
build - build the recipe
clean - clean the recipe's folder
node - run recipe on Node.js
browser - run recipe on browser
ci - test this recipe during CI build
```
where the 'Targets' section would display the available targets one could use. 

If the user ran a non-existent recipe, they would get this error message.
```
Error: Recipe, '<recipe name>,' does not exist. See list below for all recipes:
<same output as `make`'s recipe list>
```
If the user ran a non-existent target for a recipe (e.g. `make RoutingHashHalogen foo`), it would print:
```
Error: Recipe, 'RoutingHashHalogen,' does not have target, 'foo.'
Please rerun this command using one of the below valid targets for 'RoutingHashHalogen':
<same output as the target list from above>
```

Part of me thinks this should be done by specifying a `makefile` in each recipe and use the [includes](https://www.gnu.org/software/make/manual/make.html#Include) directive to include them in the root folder's `makefile`.

**Comment by milesfrain** [comment]
A makefile per recipe could work, but this might introduce a bunch of duplicated content.

With a `clean` per recipe, should this delete the common `spago build` output, or just the `parcel` content in that recipe's directory? I think `git clean -xdf` is good enough for most situations.

**Comment by milesfrain** [comment]
* `browser` compatibility can be confirmed by checking for a `dev` directory.
* A lightweight way to enable checks for `node` compatibility could be to just add an empty `worksWithNode.txt` file.

In either case, I think most users will be starting from a table on the cookbook homepage (likely containing the columns: `recipe | description | node? | browser?`) rather than discovering these recipes via CLI.

Building a set of CLI menus with makefiles is possible, but it's not the common use-case. We may have a better return on investment with building a homepage and adding more recipes, rather than focusing too much on a completely polished CLI at this early stage.

**Comment by JordanMartinez** [comment]
> Building a set of CLI menus with makefiles is possible, but it's not the common use-case. We may have a better return on investment with building a homepage and adding more recipes, rather than focusing too much on a completely polished CLI at this early stage.

True. My only concern is that, if we have to change CI later because of some issue, that may require a lot of updating.

Regardless, I think you're right about the CLI menus. Most people will be looking at the Readme (I presume) for discovery, not via `make` commands. I also think that this issue has slowed things down too much.

**Comment by JordanMartinez** [comment]
@milesfrain Do you think this issue can be closed? We might need to clean up some of the instructions for how to add a recipe, but I think the majority of this has been finished.
