### ISSUE TITLE
simple - but not trivially simple - parser example

### ISSUE THREAD

**Issue by afcondon** [JordanMartinez/purescript-cookbook#240]
**SimplishParser**

```
simpleASTParser
```

**Recipe Description**

I spent my free time this morning working on porting a pretty simple Parsec-based parser from Haskell and, despite knowing Haskell and PureScript quite well i got tripped up on some of the differences and i think a complete beginner would have been tripped up a little more often (by String !== [Char] just to start with). 

Recursive parsers behave differently - i would say a little less elegantly - in PureScript and there are some good notes on this: [here](https://github.com/Thimoteus/SandScript/wiki/2.-Parsing-recursively).

Altho you might think that Haskell would still be the first choice for writing a parser, i think it would absolutely be worthwhile having a recipe here that shows a super simple AST and a parser for it so that people could "copy and extend" without having to wrassle with Haskell translation.

**Comment by JordanMartinez** [comment]
What counts as a "super simple AST"? Could you provide an example of an expression the parser would parse?

**Comment by afcondon** [comment]
My idea was when / if i get this working https://github.com/afcondon/language-dot/tree/master/src, i would knock it down to a minimal example and turn that into a recipe. i would think but haven't checked that even simple mathematical / calculator expression like `(2 + 2) * (4 / 5)` or whatever would do.

The key thing that you'd need to know is that strictness means you have to turn this Haskell: 
```haskell
parseGraph :: Parser Graph
parseGraph =
    ( Graph <$>
          parseGraphStrictness
      <*> parseGraphDirectedness
      <*> optionMaybe parseId
      <*> parseStatementList
    )
    <?> "graph"
```
into this PureScript:
```haskell
parseGraph :: Parser Graph
parseGraph = fix $ \p -> 
    ( Graph <$>
          parseGraphStrictness
      <*> parseGraphDirectedness
      <*> optionMaybe parseId
      <*> (parseStatementList p)
    )
    <?> "graph"
```

i don't think you can easily arrive at that construction from the cycle in declaration compiler error, so that's a key thing to show. But also, as i said, the `String` is not `[Char]` difference from Haskell would bite the naive translator.

**Comment by JordanMartinez** [comment]
Gotcha.

Then, let's say this recipe should be able to parse valid mathematical expression:
- atomic pieces: integers between `bottom :: Int` and `top :: Int`
- basic operations: `+`, `-`, `*`, `/`
- a negating character: `-` that immediately precedes a digit
- parenthesis: `(` and `)`

**Comment by milesfrain** [comment]
>     * a negating character: `-` that immediately precedes a digit

This might end up being more convenient than how PS currently parses negation.
