### ISSUE TITLE
Post requests with PureScript Affjax and Argonaut

### ISSUE THREAD

**Issue by afcondon** [JordanMartinez/purescript-cookbook#247]
**Recipe Name**

```
AffjaxPostExample
```

**Recipe Description**

Update of blogpost here: https://codingstruggles.com/purescript/post-request-with-purescript-affjax-and-argonaut.html

The post is pretty self-documenting but, being 4 years old, is written using Eff { row } instead of Effect, seems like a very easy port. I'll put a comment on the blog letting the author know i've created this issue.

> In this post I will explain how make a simple ajax call in PureScript, using Affjax and Argonaut.

>For this example I’m going to use http://jsonplaceholder.typicode.com/ as my API endpoints. We will make a POST call to the /posts endpoint to create a new post.

**Comment by JordanMartinez** [comment]
Mind submitting a PR for this?

**Comment by afcondon** [comment]
i haven't done the conversion yet to be able to PR it, just lodged this request while it occurred to me as i happened on the page and when i'd checked there didn't seem to be a recipe in the book yet that does it

**Comment by afcondon** [comment]
PR incoming for this now
