### ISSUE TITLE
Tic-Tac-Toe

### ISSUE THREAD

**Issue by ptrfrncsmrph** [JordanMartinez/purescript-cookbook#251]
**Recipe Name**

```
TicTacToeReactHooks
```

**Recipe Description**

Should be a functioning tic-tac-toe game that:
- Indicates when a player has won the game,
- Stores a game’s history as a game progresses,
- Allows players to review a game’s history and see previous versions of a game’s board.

The idea is to recreate [this example from the official React docs](https://reactjs.org/tutorial/tutorial.html).

**Comment by ptrfrncsmrph** [comment]
I was planning on working on this anyway and wanted to see if this would be a welcome addition to the cookbook. I think it might be valuable for the following reasons:
- it's a small enough example to be manageable in a single file, while being complicated enough to involve multiple nested components (something not exemplified in the existing `ReactHooks` recipes)
- as the main tutorial used by ReactJS.org, it might be familiar with new users of PureScript coming from React in JavaScript/TypeScript

I don't seem to have the option to assign myself to the issue

**Comment by JordanMartinez** [comment]
I've assigned you to this issue. Sounds like a good recipe to me.
