### ISSUE TITLE
Add capability pattern as node-only recipe

### ISSUE THREAD

**Issue by milesfrain** [JordanMartinez/purescript-cookbook#256]
**Recipe Name**
```
CapabilityPatternNode
```

**Recipe Description**

See the readme in https://github.com/afcondon/purescript-capability-pattern

@afcondon, do we have your permission to include your project in the cookbook, and/or would you like to make the cookbook PR?

**Comment by afcondon** [comment]
Oh for sure, i'd love it to live there. I'll have a look at recasting it as a recipe later today.

**Comment by milesfrain** [comment]
For the node-only recipes, I believe it's fine for it to continue to be multiple modules/files.

**Comment by afcondon** [comment]
I'll PR something for your comments in a while - possibly too late for EOD West Coast...as a recipe i think it would be best if it didn't error in the Test case even tho that's what you really want to show happening to explain `assert`, perhaps that's functionality that's best explained else where tho...also you might consider it a family of recipes and add `Aff` and `Except` variations so as to allow progressive learning?

**Comment by afcondon** [comment]
Just FYI - i've now added an ExceptT enhanced example too. 

It's on a separate branch so as not to mess up existing PR. You might think whether you'd like to incorporate into this recipe or a separate one and i'd be happy to PR it.

If i can get the checked-exceptions stuff in too then i think that'll certainly do me personally as an application container for the time being - that would bring it up to parity with that RAVE library that @JordanMartinez linked in Discourse...for which i could find no actual examples.

**Comment by milesfrain** [comment]
PR in #257
