### ISSUE TITLE
RunCapabilityPatternNode

### ISSUE THREAD

**Issue by Mateiadrielrafael** [JordanMartinez/purescript-cookbook#265]
**Recipe Name**

```
RunCapabilityPatternNode
```

Each recipe name must be unique. Use PascalCase.

**Recipe Description**

What should this recipe do?

Similar to the existing CapabilityPatternNode recipe, but implemented using purescript-run and free monads

**Comment by Mateiadrielrafael** [comment]
I can implement this myself, but can't figure out how to assign myself from the github app.

**Comment by milesfrain** [comment]
> can't figure out how to assign myself from the github app

Yeah, that's a really annoying github "feature". You can't self-assign to issues unless you're a collaborator with direct write-access to the repo.

**Comment by JordanMartinez** [comment]
@milesfrain Do you think there's a GitHub Action we could add where someone who makes a comment that satisfies some criteria (e.g. they write "self-assign" as a single comment) will make GitHub assign the issue to them? Might be useful to build such a tool across all PureScript repos (assuming it hasn't been done already).

**Comment by milesfrain** [comment]
I think you can only have a github action trigger on comments to PRs.
Some projects work around this with a bot that looks for chatroom self-assign request comments.
https://github.com/isaacs/github/issues/153
