### ISSUE TITLE
React recipes broken on try.ps.ai

### ISSUE THREAD

**Issue by ptrfrncsmrph** [JordanMartinez/purescript-cookbook#284]
**Describe the bug**

The `try.ps.ai` links to `*ReactHooks` recipes are broken. There was a [related issue](https://github.com/purescript/trypurescript/issues/236) with TryPureScript that was fixed [here](https://github.com/purescript/trypurescript/pull/237). So it seems like the issue is just that `try.ps.ai` is not up-to-date with TryPureScript. I don't know how `try.ps.ai` is maintained; apologies if this is not the right place to open an issue.

**To Reproduce**

1. Go to the [`README` for this project](https://github.com/JordanMartinez/purescript-cookbook/blob/master/README.md)
2. Click on any **try** link for a `*ReactHooks` recipe (such as `HelloReactHooks`: https://try.ps.ai/?github=JordanMartinez/purescript-cookbook/master/recipes/HelloReactHooks/src/Main.purs)
3. Open browser console
4. See error `Uncaught TypeError: React.forwardRef is not a function`

**Expected behavior**

Would expect the same behavior as loading the same source code in `try.purescript.org` editor.

**Screenshots**

**Environment:**

- Browser (if applicable): Chrome & Firefox
- Node Version:
- Spago Version:
- PureScript Version:

**Additional context**

**Comment by milesfrain** [comment]
> I don't know how `try.ps.ai` is maintained

It's currently hosted from this branch: https://github.com/milesfrain/tps/tree/demo-fixes

I just made a quick edit to incorporate your fix, so the react recipes should be working now.

Longer-term, we should migrate back to the official https://try.purescript.org. Todo items for cookbook compatibility are:
- Allow non-main modules https://github.com/purescript/trypurescript/issues/174. You can see the error in the following links: 
- I think we should remove the leading slash `/` requirement when loading a source file from gh repos. Another workaround is to update all recipe links in the readme to add the leading slash. Related issue is https://github.com/purescript/trypurescript/pull/218. For examples, compare:
  - https://try.ps.ai/?github=JordanMartinez/purescript-cookbook/master/recipes/HelloReactHooks/src/Main.purs (current cookbook links, no leading slash)

  - https://try.purescript.org/?github=JordanMartinez/purescript-cookbook/master/recipes/HelloReactHooks/src/Main.purs (ported to official site without leading slash, doesn't load)
  - https://try.purescript.org/?github=/JordanMartinez/purescript-cookbook/master/recipes/HelloReactHooks/src/Main.purs (loads with leading slash, but needs above module name fix)

**Comment by thomashoneyman** [comment]
@milesfrain I would really like to curate a collection of issues on the Try PureScript issue tracker and organize some kind of hackathon to bring it up to feature parity with the work you’ve done on try.ps.ai. I’m able to review incoming pull requests and get them merged so long as they’re manageable sizes.

**Comment by ptrfrncsmrph** [comment]
> I just made a quick edit to incorporate your fix, so the react recipes should be working now.

Yes that looks to have fixed it 👍
