### ISSUE TITLE
CatGifsHalogenHooks image display is broken.

### ISSUE THREAD

**Issue by ptrfrncsmrph** [JordanMartinez/purescript-cookbook#289]
**Describe the bug**

The response type for the Giphy API used in the `CatGifsHalogenHooks` recipe has changed, and the images fail to display as a result.

**To Reproduce**

You can observe this behavior on the [`try.ps.ai` link](https://try.ps.ai/?github=JordanMartinez/purescript-cookbook/master/recipes/CatGifsHalogenHooks/src/Main.purs). The GET request to the `api.giphy.com` endpoint succeeds, but the UI displays the error message "I could not load a random cat for some reason."

**Expected behavior**

Should be able to see cat GIFs in the UI.

**Screenshots**

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/26548438/153892930-330d736a-d00a-48a2-812a-d6ff41fb3eed.png">

**Environment:**

- Browser (if applicable): Firefox / Chrome
- Node Version:
- Spago Version:
- PureScript Version:

**Additional context**

There was a fix for the React Hooks recipe here: https://github.com/JordanMartinez/purescript-cookbook/pull/288
Also, can look at the Elm implementation here to see how the JSON response is decoded there: https://elm-lang.org/examples/cat-gifs

**Comment by neilhan** [comment]
I am new to Purescript. Codec.Argonaut is cryptic to me. I am only able to come up with a brut-force decoder, would this work? If it's ok, I can fix up a PR. cheers.
`decodeCatJson :: AC.Json -> Either CA.JsonDecodeError { data :: { images :: { downsized :: { url :: String } } } }
decodeCatJson = CA.decode
  $ CA.object "data"
  $ CAR.record
      { data: CA.object "images" $ CAR.record
          { images: CA.object "downsized" $ CAR.record
              { downsized: CA.object "url" $ CAR.record
                  { url: CA.string }
              }
          }
      }`

**Comment by JordanMartinez** [comment]
That looks right.

**Comment by ptrfrncsmrph** [comment]
Yeah, something like that would work 👍 . There are a few ways of going about decoding JSON. The `CA.decode` approach takes a `Codec` and "runs it" on some input. Another approach is to just use the inferred `DecodeJson` instance for the response type: https://try.purescript.org/?gist=d4b93117c34c89124da7869c41edd14b (which might seem magical 😄 but this is a really nice feature of PureScript). There are probably other ways of going about this too, I haven't used all of the `argonaut` libraries.

**Comment by neilhan** [comment]
Cool, let me do a PR then.
