### ISSUE TITLE
Re-enable the 'try' link for browser-based recipes

### ISSUE THREAD

**Issue by JordanMartinez** [JordanMartinez/purescript-cookbook#293]
In #292, we disabled the `try` links because there are still some issues with Try PureScript. Once that gets resolved, we should update the readme to include the 'try' link again (`./scrips/generateRecipeTable.sh`)

**Comment by ptrfrncsmrph** [comment]
Might already be obvious, but just noting: if https://github.com/JordanMartinez/purescript-cookbook/pull/294 is merged, I think we'll also need to shim React 18 in Try PureScript (currently on 16.x) before enabling the `try` links for React recipes.

**Comment by JordanMartinez** [comment]
That's correct. It also means we should update the `purescript-react`/`purescript-react-dom` libraries to use React 18 and verify they still work. The `package.json` files are on React 16.
