### ISSUE TITLE
Require all recipes to be licensed under MIT or next most-permissive license

### ISSUE THREAD

**Issue by JordanMartinez** [JordanMartinez/purescript-cookbook#32]
So that others can build upon such work without having license issues.

**Comment by JordanMartinez** [comment]
I think the easiest way to do this would be to include a LICENSE file in each recipe folder.

**Comment by milesfrain** [comment]
I expect the [repo license](https://github.com/JordanMartinez/purescript-cookbook/blob/master/LICENSE) would cover all recipes.

**Comment by JordanMartinez** [comment]
True, but we might want to clarify that in #31's contributing.md file.
