### ISSUE TITLE
Autogenerate Readme's list of recipes

### ISSUE THREAD

**Issue by JordanMartinez** [JordanMartinez/purescript-cookbook#34]
See [this comment](https://github.com/JordanMartinez/purescript-cookbook/pull/31#issuecomment-643796213) for more context.

**Comment by and-pete** [comment]
In the meantime, the `RoutingLog` link in the first column of the ReadMe table is broken (as it refers to `RoutingLog` instead of the current `RoutingHashLog`). Also the corresponding text in the Description column refers to a misspelled `rouing` library. :)

**Comment by JordanMartinez** [comment]
D'oh! Thanks for making us aware of that!

**Comment by milesfrain** [comment]
Quick fix for above included in https://github.com/JordanMartinez/purescript-cookbook/commit/27162d0ca3235c927415069c2cf234b0f801ae93

**Comment by JordanMartinez** [comment]
Thanks @milesfrain for fixing that!
