### ISSUE TITLE
Include resources to `make` for developers unfamiliar with it

### ISSUE THREAD

**Issue by JordanMartinez** [JordanMartinez/purescript-cookbook#43]
Here's resources I've found that help one get up-to-speed quickly. I think this could be added (or even just kept here as an issue) in case others want to understand what we're doing and why:
- [Official Manual (somewhat hard to read/understand)](https://www.gnu.org/software/make/manual/make.html)
- [Makefile tutorial (quick summary of manual with missing parts)](https://makefiletutorial.com/)
- [Make Guide (slides)](http://martinvseticka.eu/temp/make/normal.html)
- [Make Cheatsheet](http://eduardolezcano.com/wp-content/uploads/2016/06/make_cheatsheet.pdf)
- [Automatic Variables (i.e. what `$*`, `$%`, `$@`, etc. mean)](https://www.gnu.org/software/make/manual/make.html#Automatic-Variables)
- [Your Makefiles are wrong](https://tech.davis-hansson.com/p/make/)

**Comment by milesfrain** [comment]
I like the `>` instead of tabs tip in that last link.
My previous workaround for that was to put this in `.vimrc`:
```vim
" Disable expand tab for makefiles
autocmd FileType make setlocal noexpandtab
```

**Comment by JordanMartinez** [comment]
Agreed. I've opened an issue for it.

**Comment by JordanMartinez** [comment]
If I'm understanding them correctly, I think I'd also like to add these settings. @milesfrain Thoughts?:
```
.SHELLFLAGS := -eu -o pipefail -c
MAKEFLAGS += --warn-undefined-variables
MAKEFLAGS += --no-builtin-rules
```

**Comment by milesfrain** [comment]
Yeah, those look good too
