### ISSUE TITLE
Pending - Update Parcel to next breaking release

### ISSUE THREAD

**Issue by JordanMartinez** [JordanMartinez/purescript-cookbook#47]
Parcel `v2.0.0-beta.1` was just released. We'll likely upgrade to the stable version once it's been released:
https://github.com/parcel-bundler/parcel/releases

**Comment by andys8** [comment]
Can be closed since we already updated to 2.6.2

https://github.com/JordanMartinez/purescript-cookbook/blob/3bbeca8bfe23d73a5c02d978b1a47286a22df262/package.json#L5

**Comment by JordanMartinez** [comment]
Thanks!
