### ISSUE TITLE
Add additional shell and make flags to improve reliability of `makefile`

### ISSUE THREAD

**Issue by JordanMartinez** [JordanMartinez/purescript-cookbook#51]
Add these flags based on [Your makefiles are wrong](https://tech.davis-hansson.com/p/make/) and the overview of [the shell flags](http://redsymbol.net/articles/unofficial-bash-strict-mode/)
```make
.SHELLFLAGS := -eu -o pipefail
MAKEFLAGS += --warn-undefined-variables
MAKEFLAGS += --no-builtin-rules
```

While "Your makefiles are wrong" also recommends adding the `-c` shell flag, [which might refer to the `-C` flag](https://ss64.com/bash/set.html) flag, it seems like that isn't desired because we overwrite the repo's README.md file.

**Comment by JordanMartinez** [comment]
The shell flags only seem to work if the default shell is set to `bash`. The default is `sh`.

**Comment by milesfrain** [comment]
Not sure what that (lowercase) -c flag is referring to. Might be a typo, but in either case, I don't think we want it.

**Comment by JordanMartinez** [comment]
If I remove that `-c`, it produces this error when I run `make`:
```
$ make
bash: ls recipes: No such file or directory
bash: echo Use \"make RecipeName-target\" to run a recipe: No such file or directory
makefile:40: recipe for target 'list' failed
make: *** [list] Error 1
```
So, I'm not sure why, but it does seem necessary. The guide doesn't explain why.
