### ISSUE TITLE
Determine special file extension for distinguishing special `make`-related files

### ISSUE THREAD

**Issue by JordanMartinez** [JordanMartinez/purescript-cookbook#59]
See [this comment](https://github.com/JordanMartinez/purescript-cookbook/pull/58#issuecomment-646907454) for more context.

**Comment by milesfrain** [comment]
I figured `.md` would be convenient if folks are just clicking around in the repo.
Content optional, but the note within it seems helpful to describe why it's there.
https://github.com/JordanMartinez/purescript-cookbook/blob/master/recipes/HelloWorld/nodeSupported.md

**Comment by JordanMartinez** [comment]
Makes sense. Might help if I actually opened and read the file :sweat_smile:
