### ISSUE TITLE
Which package manager to use: npm, yarn, or pnpm?

### ISSUE THREAD

**Issue by JordanMartinez** [JordanMartinez/purescript-cookbook#74]
Due to #69, I thought it would be better if we discuss this here. See [my comment in #56](https://github.com/JordanMartinez/purescript-cookbook/issues/56#issuecomment-647140196) for more context.

The advantage of using `npm` is that people are already familiar with it and it's already installed on their computer if they are running these recipes in the first place. However, it is the slowest of all three package managers and it does not solve [the doppelganger problem](https://rushjs.io/pages/advanced/npm_doppelgangers/).

The advantage of using `yarn` is that it's the next most familiar package manager aside from `npm` and it's only slightly slower than `pnpm`. However, it doesn't solve the doppelganger problem and I think it's CLI is a bit different than `npm`. So there would be a bit of a learning curve.

The advantage of using `pnpm` is that [it's the fastest of all three package managers](https://pnpm.js.org/en/benchmark) when downloading packages, and it solves the doppelganger problem. It's only disadvantage is that less people know about it. However, it seems that any calls of `npm <command>` can be replaced with `pnpm <command>`. So it's actually more familiar than most people realize. "Installing yet another npm dependency" isn't that big of a deal, IMHO, in this repo because of two reasons. First, we will already be installing numerous npm packages once we get more recipes. Second, all of these packages, including the tools used by this repo (e.g. purescript, spago, parcel), are installed locally, not globally. Finally, this code will likely be wrapped in a `make `command.

While we don't yet have enough recipes to create the doppelganger problem, I am still in favor of using `pnpm`.

**Comment by milesfrain** [comment]
I'm open to a pnpm PR, but let's decouple that from other changes (like adding BigInts recipe in #69).

**Comment by JordanMartinez** [comment]
Sounds good!
