### ISSUE TITLE
Port Elm Examples

### ISSUE THREAD

**Issue by milesfrain** [JordanMartinez/purescript-cookbook#86]
Proposing we include some (or all) of the [Elm Examples](https://elm-lang.org/examples).

Spork made a [partial start](https://github.com/natefaubion/purescript-spork/tree/master/examples) with this.

These are all web-focused, but some can also have node equivalents. For example, [Numbers](https://elm-lang.org/examples/numbers) doesn't _need_ a roll button. Also, let's rename that one to "Dice".

I'm thinking naming convention could be:
* DiceHalogen - click button to roll
* DiceLog - logs roll to console
* CatGIFsHalogen - this makes more sense for web
* CatGIFsLog - although I guess it could also just log a link that you can click on
* CatGIFsConcur - may demo other frameworks too

It might also be good to make sure each web recipe exists in a single `Main.purs` so we can present TryPureScript links in the table. I'll add a TPS feature that let's us load directly from a file in a repo (so we can bypass the gist upload step).

Added by Jordan with notes on status:
- HTML
    - [x] Hello
    - [x] Groceries
    - [ ] Shapes (blocked until either package set includes Halogen SVG library, we do FFI, or use non-Halogen backend)
- User Input
    - [x] Buttons
    - [x] Text Fields
    - [ ] Forms (blocked until either package set includes Halogen hooks version of Formless, do custom form code, or use non-Halogen backend)
- Random
    - [x] Numbers
    - [x] Cards (note: doesn't use uniform generator when choosing next card)
    - [x] Positions
- HTTP
    - [x] Book
    - [x] Cat GIFs
- Time
    - [x] Time
    - [ ] Clock (blocked until either package set includes Halogen SVG library, we do FFI, or use non-Halogen backend)
- Files
    - [x] Upload
    - [x] Drag-and-Drop
    - [x] Image Previews

**Comment by paluh** [comment]
@milesfrain Do you mean specifically halogen recipes here?

In such a case maybe it should be reflected in the title of the issue so separate tickets could be created for other frameworks.

**Comment by milesfrain** [comment]
No specific framework in mind. Updated list to include a Concur example.

**Comment by JordanMartinez** [comment]
@milesfrain Good idea! 

@paluh When we have two recpies that do the same thing using different libraries, it looks like we'll be adding a suffix for that library. For example, `RecipeNameHalogen` for Halogen, `RecipeNameReact` for React, and `RecipeNameConcur` for Concur. If we use the hook version, I guess we would write `RecipeNameHalogenHooks` or something.

**Comment by milesfrain** [comment]
It's tempting to just let the Hooks version of Halogen be the default, as it is with React.

**Comment by JordanMartinez** [comment]
I've added a checkbox for each Elm example in the opening thread to help track what has and hasn't been done yet.

**Comment by JordanMartinez** [comment]
Note: we won't be able to do the `HTML - Shapes` one until [purescript-halogen-svg](https://github.com/statebox/purescript-halogen-svg) is a part of the package set. They haven't been that responsive in the issues opened, so I don't know when/if this will happen.

**Comment by JordanMartinez** [comment]
I also got stuck on "User Input > Text Fields" because we don't seem to have a `reverse :: String -> String` function... :open_mouth:

**Comment by JordanMartinez** [comment]
@milesfrain Do you think it would be good to prefix these recipe names with `Elm` (e.g. `ElmCardsHalogen`), so that all of them appear together in the readme?

**Comment by milesfrain** [comment]
I don't think that's necessary, and might be a bit misleading.

If anything, I think it's fine to just create a list of links to those recipes in this issue. There's a risk that those links will break without CI help. We could also transfer that list to a separate readme that the community is free to update manually as they wish.

**Comment by JordanMartinez** [comment]
> Edit: I see you're mentioning "Elm Examples" in the description, so I think that is a pretty solid way for people to find these.

Ok, works for me.

**Comment by JordanMartinez** [comment]
I'm not really sure how we're going to port the Playground Elm examples. Some use animation which isn't as well-explored in Halogen as it could be.

**Comment by milesfrain** [comment]
I wouldn't worry about omitting the WebGL or Playground examples. There doesn't seem to be as much of a need for those.

**Comment by ptrfrncsmrph** [comment]
For the sake of explicitly claiming some of these tasks (as recommended in the [`CONTRIBUTING.md` guide](https://github.com/JordanMartinez/purescript-cookbook/blob/master/CONTRIBUTING.md#goal-1-claim-and-start-working-on-a-recipe-request)), I'm currently working on mirroring most of what @JordanMartinez has already implemented in Halogen, in React Hooks. Current status:
- Random (all pending review at time of writing)
    - [x]  NumbersReact
    - [x]  CardsReact
    - [x]  PositionsReact
- HTTP
    - [ ]  BookReact
    - [ ]  CatGifsReact
- Time
    - [ ]  TimeReact
    - [ ]  ClockReact

I'll plan on finishing the rest of these within a week's time 🙂

**Comment by JordanMartinez** [comment]
@ptrfrncsmrph Thanks for your work on that! It'll be nice for new users to compare and contrast React and Halogen from a different angle.

I should probably explicitly claim doing the Halogen examples, too, since I haven't already in this issue.

**Comment by milesfrain** [comment]
Concur list:
- [ ] HelloConcur
- [ ] GroceriesConcur
- [ ] ShapesConcur
- [ ] ButtonsConcur
- [ ] TextFieldsConcur
- [ ] FormsConcur
- [ ] NumbersConcur
- [ ] CardsConcur
- [ ] PositionsConcur
- [ ] BookConcur
- [ ] CatGifsConcur
- [ ] TimeConcur
- [ ] ClockConcur
- [ ] UploadConcur
- [ ] DragAndDropConcur
- [ ] ImagePreviewsConcur

**Comment by JordanMartinez** [comment]
Per [this comment thread](https://github.com/JordanMartinez/purescript-cookbook/pull/151#discussion_r451100553), we should update the Readmes of the recipes that port the Elm Examples' to point to the actual code examples, not the list of examples.

**Comment by JordanMartinez** [comment]
Per @milesfrain's comment above...

> I wouldn't worry about omitting the WebGL or Playground examples. There doesn't seem to be as much of a need for those.

I'm going to remove those from this issue's list of checkboxes. Besides the two blocked by Halogen SVG elems not being included in the package set and not yet implemented hooks-version of Halogen formless, we've fully ported all elm examples for Halogen.

**Comment by JordanMartinez** [comment]
@milesfrain Mind if we close out this issue and open the following 4 new issues?
- an issue for the 2 SVG-related recipes above for Halogen
- an issue for the form recipe above for Halogen
- an issue for the remaining recipes for React
- an issue for all recipes for Concur
